// Code generated by "stringer -type=State -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateClosed-0]
	_ = x[StateListen-1]
	_ = x[StateSynSent-2]
	_ = x[StateSynReceived-3]
	_ = x[StateEstablished-4]
}

const _State_name = "CLOSEDLISTENSYN-SENTSYN-RECEIVEDESTABLISHED"

var _State_index = [...]uint8{0, 6, 12, 20, 32, 43}

func (i State) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_State_index)-1 {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[idx]:_State_index[idx+1]]
}
